### ISSUE TITLE
Connector version always reports the Kafka Connect version

### ISSUE THREAD

**Issue by gharris1727** [redis-field-engineering/redis-kafka-connect#20]
Hi, I downloaded the 7.2 release of this connector, but when I called `GET /connector-plugins` it reported that the version of the connector was 3.4.0 (the version of Kafka Connect).

I would have expected the version to be either null/undefined, or 7.2.

I think this is because the connectors are using the AppInfoParser: https://github.com/redis-field-engineering/redis-kafka-connect/blob/a6c99de8e686d813463293b7acab69d147e403bc/src/main/java/com/redis/kafka/connect/RedisSinkConnector.java#L61 which always gets the version of the containing Kafka Connect worker.

**Comment by jruaux** [comment]
🎉 This issue has been resolved in `v0.7.5` ([Release Notes](https://github.com/redis-field-engineering/redis-kafka-connect/releases/tag/v0.7.5))
