### ISSUE TITLE
Sink connector ignores tasks.max argument

### ISSUE THREAD

**Issue by buinauskas** [redis-field-engineering/redis-kafka-connect#27]
We've noticed that the sink connector ignores the `tasks.max` configuration parameter entirely and there's no way to create more sink tasks. I suspect this is due to the following method that always yields a single instance of task, it ignores the `numTasks` argument entirely.
https://github.com/redis-field-engineering/redis-kafka-connect/blob/f095f81b8f0adefed177e4598022ea6b212f8f7f/core/redis-kafka-connect/src/main/java/com/redis/kafka/connect/RedisSinkConnector.java#L46

The documentation suggests that it should support it https://redis-field-engineering.github.io/redis-kafka-connect/#_sink_tasks
> The Redis Kafka Sink Connector supports running one or more tasks. You can specify the number of tasks with the tasks.max configuration property.

**Comment by jruaux** [comment]
Thanks you for reporting this and for the fix.

**Comment by jruaux** [comment]
🎉 This issue has been resolved in `v0.9.0` ([Release Notes](https://github.com/redis-field-engineering/redis-kafka-connect/releases/tag/v0.9.0))
